import tkinter as tk
from tkinter import ttk
from tkinter import messagebox as mb
from tkinter import scrolledtext as st
import empleados

class FormularioEmpleados:
    def __init__(self):
        self.empleado1=empleados.Empleados()
        self.ventana1=tk.Tk()
        self.ventana1.title("Empleados")
        self.cuaderno1 = ttk.Notebook(self.ventana1)
        self.carga_empleados()
        self.consulta_por_codigo()
        self.borrado()
        self.modificar()
        self.cuaderno1.grid(column=0, row=0, padx=30, pady=30)
        self.ventana1.mainloop()

    def carga_empleados(self):
        self.pagina1 = ttk.Frame(self.cuaderno1)
        self.cuaderno1.add(self.pagina1, text="Insertar")
        self.labelframe1=ttk.LabelFrame(self.pagina1, text="Empleado")
        self.labelframe1.grid(column=0, row=0, padx=5, pady=10)
        self.label1=ttk.Label(self.labelframe1, text="Nombre:")
        self.label1.grid(column=0, row=0, padx=4, pady=4)
        self.nombrecarga=tk.StringVar()
        self.entrynombre=ttk.Entry(self.labelframe1, textvariable=self.nombrecarga)
        self.entrynombre.grid(column=1, row=0, padx=4, pady=4)
        self.label2=ttk.Label(self.labelframe1, text="Apellido_paterno:")
        self.label2.grid(column=0, row=1, padx=4, pady=4)
        self.apellido_paternocarga=tk.StringVar()
        self.entryapellido_paterno=ttk.Entry(self.labelframe1, textvariable=self.apellido_paternocarga)
        self.entryapellido_paterno.grid(column=1, row=1, padx=4, pady=4)
        self.label3 = ttk.Label(self.labelframe1, text="Apellido_materno:")
        self.label3.grid(column=0, row=2, padx=4, pady=4)
        self.apellido_maternocarga = tk.StringVar()
        self.entryapellido_materno = ttk.Entry(self.labelframe1, textvariable=self.apellido_maternocarga)
        self.entryapellido_materno.grid(column=1, row=2, padx=4, pady=4)
        self.label4 = ttk.Label(self.labelframe1, text="Email:")
        self.label4.grid(column=0, row=3, padx=4, pady=4)
        self.emailcarga = tk.StringVar()
        self.entryemail = ttk.Entry(self.labelframe1, textvariable=self.emailcarga)
        self.entryemail.grid(column=1, row=3, padx=4, pady=4)
        self.label5 = ttk.Label(self.labelframe1, text="Fecha_contrato:")
        self.label5.grid(column=0, row=4, padx=4, pady=4)
        self.fecha_contratocarga = tk.StringVar()
        self.entryfecha_contrato = ttk.Entry(self.labelframe1, textvariable=self.fecha_contratocarga)
        self.entryfecha_contrato.grid(column=1, row=4, padx=4, pady=4)
        self.label6 = ttk.Label(self.labelframe1, text="Notas:")
        self.label6.grid(column=0, row=5, padx=4, pady=4)
        self.notascarga = tk.StringVar()
        self.entrynotas = ttk.Entry(self.labelframe1, textvariable=self.notascarga)
        self.entrynotas.grid(column=1, row=5, padx=4, pady=4)
        self.boton1=ttk.Button(self.labelframe1, text="Guardar", command=self.agregar)
        self.boton1.grid(column=1, row=6, padx=4, pady=4)

    def agregar(self):
        datos=(self.nombrecarga.get(), self.apellido_paternocarga.get(), self.apellido_maternocarga.get(), self.emailcarga.get(), self.fecha_contratocarga.get(), self.notascarga.get())
        self.empleado1.alta(datos)
        mb.showinfo("Información", "Los datos fueron cargados")
        self.nombrecarga.set("")
        self.apellido_paternocarga.set("")
        self.apellido_maternocarga.set("")
        self.emailcarga.set("")
        self.fecha_contratocarga.set("")
        self.notascarga.set("")

    def consulta_por_codigo(self):
        self.pagina2 = ttk.Frame(self.cuaderno1)
        self.cuaderno1.add(self.pagina2, text="Consulta por código")
        self.labelframe2=ttk.LabelFrame(self.pagina2, text="Empleado")
        self.labelframe2.grid(column=0, row=0, padx=5, pady=10)
        self.label1=ttk.Label(self.labelframe2, text="Código:")
        self.label1.grid(column=0, row=0, padx=4, pady=4)
        self.codigo=tk.StringVar()
        self.entrycodigo=ttk.Entry(self.labelframe2, textvariable=self.codigo)
        self.entrycodigo.grid(column=1, row=0, padx=4, pady=4)
        self.label2=ttk.Label(self.labelframe2, text="Nombre:")
        self.label2.grid(column=0, row=1, padx=4, pady=4)
        self.nombre=tk.StringVar()
        self.entrynombre=ttk.Entry(self.labelframe2, textvariable=self.nombre, state="readonly")
        self.entrynombre.grid(column=1, row=1, padx=4, pady=4)
        self.label3=ttk.Label(self.labelframe2, text="Apellido_paterno:")
        self.label3.grid(column=0, row=2, padx=4, pady=4)
        self.apellido_paterno=tk.StringVar()
        self.entryapellido_paterno=ttk.Entry(self.labelframe2, textvariable=self.apellido_paterno, state="readonly")
        self.entryapellido_paterno.grid(column=1, row=2, padx=4, pady=4)
        self.label4=ttk.Label(self.labelframe2, text="Apellido_materno:")
        self.label4.grid(column=0, row=3, padx=4, pady=4)
        self.apellido_materno=tk.StringVar()
        self.entryapellido_materno=ttk.Entry(self.labelframe2, textvariable=self.apellido_materno, state="readonly")
        self.entryapellido_materno.grid(column=1, row=3, padx=4, pady=4)
        self.label5=ttk.Label(self.labelframe2, text="Email:")
        self.label5.grid(column=0, row=4, padx=4, pady=4)
        self.email=tk.StringVar()
        self.entryemail=ttk.Entry(self.labelframe2, textvariable=self.email, state="readonly")
        self.entryemail.grid(column=1, row=4, padx=4, pady=4)
        self.label6=ttk.Label(self.labelframe2, text="Fecha_contrato:")
        self.label6.grid(column=0, row=5, padx=4, pady=4)
        self.fecha_contrato=tk.StringVar()
        self.entryfecha_contrato=ttk.Entry(self.labelframe2, textvariable=self.fecha_contrato, state="readonly")
        self.entryfecha_contrato.grid(column=1, row=5, padx=4, pady=4)
        self.label7=ttk.Label(self.labelframe2, text="Notas:")
        self.label7.grid(column=0, row=6, padx=4, pady=4)
        self.notas=tk.StringVar()
        self.entrynotas=ttk.Entry(self.labelframe2, textvariable=self.notas, state="readonly")
        self.entrynotas.grid(column=1, row=6, padx=4, pady=4)
        self.boton1=ttk.Button(self.labelframe2, text="Consultar", command=self.consultar)
        self.boton1.grid(column=1, row=7, padx=4, pady=4)

    def consultar(self):
        datos=(self.codigo.get(), )
        respuesta=self.empleado1.consulta(datos)
        if len(respuesta)>0:
            self.nombre.set(respuesta[0][0])
            self.apellido_paterno.set(respuesta[0][1])
            self.apellido_materno.set(respuesta[0][2])
            self.email.set(respuesta[0][3])
            self.fecha_contrato.set(respuesta[0][4])
            self.notas.set(respuesta[0][5])
        else:
            self.nombre.set('')
            self.apellido_paterno.set('')
            self.apellido_materno.set('')
            self.email.set('')
            self.fecha_contrato.set('')
            self.notas.set('')
            mb.showinfo("Información", "No existe un artículo con dicho código")
    def borrado(self):
        self.pagina3 = ttk.Frame(self.cuaderno1)
        self.cuaderno1.add(self.pagina3, text="Borrado de empleados")
        self.labelframe4=ttk.LabelFrame(self.pagina3, text="Empleado")
        self.labelframe4.grid(column=0, row=0, padx=5, pady=10)
        self.label1=ttk.Label(self.labelframe4, text="Código:")
        self.label1.grid(column=0, row=0, padx=4, pady=4)
        self.codigoborra=tk.StringVar()
        self.entryborra=ttk.Entry(self.labelframe4, textvariable=self.codigoborra)
        self.entryborra.grid(column=1, row=0, padx=4, pady=4)
        self.boton1=ttk.Button(self.labelframe4, text="Borrar", command=self.borrar)
        self.boton1.grid(column=1, row=1, padx=4, pady=4)

    def borrar(self):
        datos=(self.codigoborra.get(), )
        cantidad=self.empleado1.baja(datos)
        if cantidad==1:
            mb.showinfo("Información", "Se borró el empleado con dicho código")
        else:
            mb.showinfo("Información", "No existe un empleado con dicho código")

    def modificar(self):
        self.pagina4 = ttk.Frame(self.cuaderno1)
        self.cuaderno1.add(self.pagina4, text="Modificar empleado")
        self.labelframe5 = ttk.LabelFrame(self.pagina4, text="Empleado")
        self.labelframe5.grid(column=0, row=0, padx=5, pady=10)
        self.label1 = ttk.Label(self.labelframe5, text="Código:")
        self.label1.grid(column=0, row=0, padx=4, pady=4)
        self.codigomod = tk.StringVar()
        self.entrycodigo = ttk.Entry(self.labelframe5, textvariable=self.codigomod)
        self.entrycodigo.grid(column=1, row=0, padx=4, pady=4)
        self.label2 = ttk.Label(self.labelframe5, text="Nombre:")
        self.label2.grid(column=0, row=1, padx=4, pady=4)
        self.nombremod=tk.StringVar()
        self.entrynombre=ttk.Entry(self.labelframe5, textvariable=self.nombremod)
        self.entrynombre.grid(column=1, row=1, padx=4, pady=4)
        self.label3 = ttk.Label(self.labelframe5, text="Apellido_paterno:")
        self.label3.grid(column=0, row=2, padx=4, pady=4)
        self.apellido_paternomod = tk.StringVar()
        self.entryapellido_paterno = ttk.Entry(self.labelframe5, textvariable=self.apellido_paternomod)
        self.entryapellido_paterno.grid(column=1, row=2, padx=4, pady=4)
        self.label4 = ttk.Label(self.labelframe5, text="Apellido_materno:")
        self.label4.grid(column=0, row=3, padx=4, pady=4)
        self.apellido_maternomod = tk.StringVar()
        self.entryapellido_materno = ttk.Entry(self.labelframe5, textvariable=self.apellido_maternomod)
        self.entryapellido_materno.grid(column=1, row=3, padx=4, pady=4)
        self.label5 = ttk.Label(self.labelframe5, text="Email:")
        self.label5.grid(column=0, row=4, padx=4, pady=4)
        self.emailmod = tk.StringVar()
        self.entryemail = ttk.Entry(self.labelframe5, textvariable=self.emailmod)
        self.entryemail.grid(column=1, row=4, padx=4, pady=4)
        self.label6 = ttk.Label(self.labelframe5, text="Fecha_contrato:")
        self.label6.grid(column=0, row=5, padx=4, pady=4)
        self.fecha_contratomod = tk.StringVar()
        self.entryfecha_contrato = ttk.Entry(self.labelframe5, textvariable=self.fecha_contratomod)
        self.entryfecha_contrato.grid(column=1, row=5, padx=4, pady=4)
        self.label7 = ttk.Label(self.labelframe5, text="Notas:")
        self.label7.grid(column=0, row=6, padx=4, pady=4)
        self.notasmod = tk.StringVar()
        self.entrynotas = ttk.Entry(self.labelframe5, textvariable=self.notasmod)
        self.entrynotas.grid(column=1, row=6, padx=4, pady=4)

        self.boton2 = ttk.Button(self.labelframe5, text="Modificar", command=self.modifica)
        self.boton2.grid(column=1, row=7, padx=4, pady=4)

    def modifica(self):
        datos = (self.nombremod.get(), self.apellido_paternomod.get(), self.apellido_maternomod.get(), self.emailmod.get(), self.fecha_contratomod.get(), self.notasmod.get(), self.codigomod.get())
        cantidad = self.empleado1.modificacion(datos)
        if cantidad == 1:
            mb.showinfo("Información", "Se modificó el empleado")
        else:
            mb.showinfo("Información", "No existe un empleado con dicho código")
aplicacion1=FormularioEmpleados()